status = error
name = PropertiesConfig

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %msg%n

rootLogger.level = off
rootLogger.appenderRef.stdout.ref = STDOUT

